color_theme = "/home/fractal-tess/.config/btop/themes/matugen.theme"
theme_background = False
truecolor = True
force_tty = False
update_ms = 2000
proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = False
cpu_graph_upper = "total"
cpu_graph_lower = "user"
disk_free_priv = False
mem_graphs = True
net_download = "100 Mbit/s"
net_upload = "100 Mbit/s"
net_auto = True
net_sync = True
show_battery = True
vim_keys = True
rounded_corners = True
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
