$image = ~/wallpapers/new/Abend.png
$background = rgba(131319ff)
$error = rgba(ffb4abff)
$error_container = rgba(93000aff)
$inverse_on_surface = rgba(312f37ff)
$inverse_primary = rgba(5b4ebcff)
$inverse_surface = rgba(e5e1ebff)
$on_background = rgba(e5e1ebff)
$on_error = rgba(690005ff)
$on_error_container = rgba(ffdad6ff)
$on_primary = rgba(2b168cff)
$on_primary_container = rgba(ede8ffff)
$on_primary_fixed = rgba(170065ff)
$on_primary_fixed_variant = rgba(4334a2ff)
$on_secondary = rgba(2f2b54ff)
$on_secondary_container = rgba(e2dcffff)
$on_secondary_fixed = rgba(1a163dff)
$on_secondary_fixed_variant = rgba(46426cff)
$on_surface = rgba(e5e1ebff)
$on_surface_variant = rgba(c8c4d5ff)
$on_tertiary = rgba(502400ff)
$on_tertiary_container = rgba(ffe6d8ff)
$on_tertiary_fixed = rgba(311300ff)
$on_tertiary_fixed_variant = rgba(723600ff)
$outline = rgba(928f9eff)
$outline_variant = rgba(474552ff)
$primary = rgba(c7bffffff)
$primary_container = rgba(493ba9ff)
$primary_fixed = rgba(e4dfffff)
$primary_fixed_dim = rgba(c7bffffff)
$scrim = rgba(000000ff)
$secondary = rgba(c7c1f3ff)
$secondary_container = rgba(46426cff)
$secondary_fixed = rgba(e4dfffff)
$secondary_fixed_dim = rgba(c7c1f3ff)
$shadow = rgba(000000ff)
$source_color = rgba(493ba9ff)
$surface = rgba(131319ff)
$surface_bright = rgba(3a3840ff)
$surface_container = rgba(201f26ff)
$surface_container_high = rgba(2a2930ff)
$surface_container_highest = rgba(35343bff)
$surface_container_low = rgba(1c1b22ff)
$surface_container_lowest = rgba(0e0d14ff)
$surface_dim = rgba(131319ff)
$surface_tint = rgba(c7bffffff)
$surface_variant = rgba(474552ff)
$tertiary = rgba(ffb787ff)
$tertiary_container = rgba(7c3b00ff)
$tertiary_fixed = rgba(ffdcc7ff)
$tertiary_fixed_dim = rgba(ffb787ff)
