[[mgr.prepend_keymap]]
on   = "y"
run  = [
  'shell -- case "$(file -b --mime-type %h)" in image/*) wl-copy -t "$(file -b --mime-type %h)" < %h ;; *) wl-copy < %h ;; esac',
  "yank",
]
desc = "Copy file content to system clipboard and yank"

[[mgr.prepend_keymap]]
on   = ["c", "z"]
run  = "plugin zip"
desc = "Zip hovered file/dir"
