keys:
  - &vd age1u0l6gx835zd0ulvsz2gmqx65chaqyv0vflnkehu3duzy4znnqc3qpmj4rw
  - &neo age10tprfx4m37fahf3sz2hk9vvpte7kmjgmptnqhs8xhqwcn5vcsges047kwh
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *vd
          - *neo
