hl.config({ animations = { enabled = true } })

hl.curve("smoothFast", { type = "bezier", points = { { 0.4, 0 }, { 0.2, 1 } } })
hl.curve("smoothSlow", { type = "bezier", points = { { 0, 0 }, { 0.2, 1 } } })
hl.curve("easeInSleek", { type = "bezier", points = { { 0.55, 0 }, { 0.1, 1 } } })
hl.curve("easeOutSleek", { type = "bezier", points = { { 0.1, 0 }, { 0.45, 1 } } })
hl.curve("softGlide", { type = "bezier", points = { { 0.3, 0 }, { 0.3, 1 } } })
hl.curve("gentleCurve", { type = "bezier", points = { { 0.25, 0.1 }, { 0.35, 0.95 } } })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "smoothSlow" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "smoothFast" })
hl.animation({ leaf = "windows", enabled = true, speed = 2.2, bezier = "softGlide", style = "slide" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 2.2, bezier = "softGlide", style = "popin" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.2, bezier = "easeOutSleek", style = "popin" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "easeInSleek" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "easeOutSleek" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "gentleCurve" })
hl.animation({ leaf = "layers", enabled = true, speed = 2.1, bezier = "softGlide", style = "slide" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 2.5, bezier = "softGlide", style = "popin" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 2.5, bezier = "easeOutSleek", style = "popin" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "easeInSleek" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "easeOutSleek" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2, bezier = "softGlide", style = "slidevert" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 2, bezier = "softGlide", style = "slidevert" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 2, bezier = "easeOutSleek", style = "slidevert" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "gentleCurve" })
