#################
### AUTOSTART ###
#################

exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = ~/nixos/scripts/wallpaper/wallpaper.sh restore
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = wl-paste --watch cliphist store
exec-once = blueman-applet
exec-once = nm-applet
exec-once = hypridle
exec-once = swaync
exec-once = waybar

exec-once = handy
