###################
### MY PROGRAMS ###
###################

$mainMod = SUPER
$terminal = ghostty
$fileManager = thunar
$menu = ~/nixos/scripts/bin/rofi-launcher drun -show-icons
$browser = vivaldi --remote-debugging-port=9222
$editor = cursor
$sysmonitor = ghostty -e btop
