###################
### MY PROGRAMS ###
###################

$mainMod = SUPER
$terminal = kitty
$fileManager = thunar
$menu = ~/nixos/scripts/session/launcher drun -show-icons
$browser = vivaldi --disable-accelerated-video-decode
$editor = cursor
$sysmonitor = kitty -e btop
