term xterm-256color

font_family CaskaydiaCoveNerdFont
font_size 12.0

scrollback_lines 10000

background_opacity 0.75
background_blur 96
window_padding_width 8

map ctrl+shift+w close_window

cursor #2F81F7
cursor_text_color #6FC1FF

selection_foreground #0D1117
selection_background #E6EDF3

foreground #E6EDF3
background #0D1117

color0  #484F58
color1  #FF7B72
color2  #3FB950
color3  #D29922
color4  #58A6FF
color5  #BC8CFF
color6  #39C5CF
color7  #B1BAC4

color8  #6E7681
color9  #FFA198
color10 #56D364
color11 #E3B341
color12 #79C0FF
color13 #D2A8FF
color14 #56D4DD
color15 #FFFFFF

active_tab_foreground #0D1117
active_tab_background #58A6FF
inactive_tab_foreground #8B949E
inactive_tab_background #161B22

url_color #58A6FF

confirm_os_window_close 0
