# Hypridle configuration for Hyprland

general {
    lock_cmd = ~/nixos/scripts/display/screen lock
}

listener {
    timeout = 300
    on-timeout = ~/nixos/scripts/display/screen bright-set 10
    on-resume = ~/nixos/scripts/display/screen bright-set 100
}

listener {
    timeout = 1800
    on-timeout = ~/nixos/scripts/display/screen lock
}

listener {
    timeout = 1800
    on-timeout = ~/nixos/scripts/display/screen off
    on-resume = ~/nixos/scripts/display/screen on
}
