# hide_cursor = false
# ignore_empty_input = true

background {
    monitor =
    path = screenshot
    color = rgba(15, 15, 15, 0.0)
    blur_passes = 3
    blur_size = 4
    noise = 0.001
    vibrancy = 1
    vibrancy_darkness = 0.03
}

input-field {
    monitor =
    size = 420, 56
    outline_thickness = 2
    dots_size = 0.5
    dots_spacing = 0.15
    dots_center = false
    dots_rounding = -1
    outer_color = rgb(154, 199, 164)
    inner_color = rgba(17, 19, 21, 0.88)
    font_color = rgba(245, 247, 242, 0.85)
    fade_on_empty = false
    fade_timeout = 1000
    placeholder_text = <i>Unlock session</i>
    hide_input = false
    rounding = 18
    check_color = rgb(215, 176, 106)
    fail_color = rgb(211, 109, 109)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<span color='#f5f7f2'>$(date +"%H:%M")</span>"
    color = #F5F7F2
    font_size = 94
    font_family = Adwaita Sans Bold
    rotate = 0
    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    text_align = center
    color = #A5ACA3
    font_size = 22
    font_family = Adwaita Sans
    rotate = 0
    position = 0, 132
    halign = center
    valign = center
}

label {
    monitor =
    text = Welcome back, Fractal-Tess
    color = rgb(143, 183, 216)
    font_size = 22
    font_family = JetBrains Mono Nerd Font ExtraBold
    position = 0, 74
    halign = center
    valign = center
}
