# Hypridle configuration for Hyprland

general {
    lock_cmd = ~/nixos/scripts/bin/screen-manager lock
}

listener {
    timeout = 300
    on-timeout = ~/nixos/scripts/bin/screen-manager 10
    on-resume = ~/nixos/scripts/bin/screen-manager 100
}

listener {
    timeout = 1800
    on-timeout = ~/nixos/scripts/bin/screen-manager lock
}

listener {
    timeout = 1800
    on-timeout = ~/nixos/scripts/bin/screen-manager off
    on-resume = ~/nixos/scripts/bin/screen-manager on
}
