ssh_config: ENC[AES256_GCM,data:PFOZCOGU9YPqkWvXeW2mKN+Y+D7oLhXG4covrnr/ZWQkBIAeCVStpIQaxf1EmBsGr8pjR89zggwkbAuou042JoqxE/+6epNKTYoimvolhQByyDKCarK61wi7btb79ScqAjdNrKBUBe2+XT7y45ovqZeIN3bJEnwe8p78y/CWZb2/TbDv1zkJZwTdSwV4C7jfpwRvgfdEtrbsBnhK03olx9ky7H127biJs52C3clMkkgeSkwV9W3JLR9tY7pc9ye19oU5nv5IsyHTzjuUBK+4f1YfYxyaYedbD+uOQYHSZ29naOVmtQZvWJaHRdUsdRJAo5oy5rnLob1RTLINdIJGi77oq2Oqb8TW67Q3yNpNWWNJgG+83kZLJwvShg/h2SUCjFpBPkxD1c8jyT71LoAucs/ijoSc0nqDlmX6efWWc2juYEn8ADCB7+XXQWqrzQBZzdx1B3EsPQiZMJobzp+5wSXOfaYvnMtrukY2rgcTeFuLnZyp+lPNtfKKofO5U3OplRtYw8k9TDASwQrgB2MeSWzVC2YXIBipPKMOWY/nUJMngXlHPsKxrA==,iv:ciO7DEUh4GfGNl7B5jmsa+T6lKSjL/rTgAYn8Jd0JUk=,tag:P2WNJGZezMqv0p/yPSHlZQ==,type:str]
sops:
    age:
        - recipient: age1u0l6gx835zd0ulvsz2gmqx65chaqyv0vflnkehu3duzy4znnqc3qpmj4rw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbTV1R0RrU0FEUzg4TjQ0
            SU9ELzljczNQR0R3RnpZZnR6eTg1Y0FGWEQ0CmpOT3hmOUsvdWtONHpkdFV2aTBm
            R0lPK0QrZkJ2ZENLZ2VnZ1pxaWZmd1UKLS0tIFdCNEI4SDE4S2p4VHJqNXdmallo
            dS9UNFBBYUhaV2J5UG42dkNCZnRNeW8K5k1lHXtN2jv1IVTrhk+XcfMWbOZUZ2eI
            YGqwctkuRs68JDCSoC28Eq1+cYQ0RzGoxM1oi/5muYdPhNX078njlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10tprfx4m37fahf3sz2hk9vvpte7kmjgmptnqhs8xhqwcn5vcsges047kwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNEY4NStFcXdISGJvOTQ2
            UmhrK0N0RkY5M1FGUXdCcThkOUZRa01MOERFCmNjR1BXbTlDTVEyenF5ZGJsMTJo
            c1JXY0VFdG1kVjUyRllOakJHSENrZlEKLS0tIElCN2hlYnR1WGVkUVg3cHlCWVFi
            aHRwZVc4ZUNLNGZkd01PV3BBQjZHZkEKABNPx5X40fIuRHOW1Evu+sS5mVXjZSJG
            mgELTUA8Q6a/glw7QIxkAbTDyuwQ62uqodJN5Tx1Qjmm/efDdY0V+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T06:32:35Z"
    mac: ENC[AES256_GCM,data:qUr8VxeS3XV7VvO9UECH6IMHZqK5G9ilzv5MEf7HJ3QDvXE+GTSkDLUC88jB81Bv4VSLr8JvQw2Aw6l+3ff7NuGUopi9tzSXkvAyIEh15cn44EMUUo0bIvaKjIa6atB513BHud5+QMQmZsc3ZX1zIOl1/BP5muG0KIran7G5OsE=,iv:93eUiDM6kaj6XRMaU3QlszhhD1C8HTIR+MmIGL5fJZI=,tag:mU+XH2XISfWGcOuG/IWPNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
