ssh_config: ENC[AES256_GCM,data:cFVIE8iqZUHnqR0JkJ0jneDrRDurHIcP4OXNzKf5aPFtB6u79BlhnIvyDal8sg8MpA9pd3JYDwPPP91IepwApsYq75WMTzp9tYZaJDqv1Ax3Fkrc+r00tfcAtb386COaiGsWn+fU6iN8pkzzfqkw99AuHav65RQ+pT06aWzzTgOgEXrj,iv:kfwnajd6cWejUGPD4/i19tmf+OkT2gpy35HuvHbWD2s=,tag:+QzVNx8hARKHJ0QaMiyAzA==,type:str]
sops:
    age:
        - recipient: age1u0l6gx835zd0ulvsz2gmqx65chaqyv0vflnkehu3duzy4znnqc3qpmj4rw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbTV1R0RrU0FEUzg4TjQ0
            SU9ELzljczNQR0R3RnpZZnR6eTg1Y0FGWEQ0CmpOT3hmOUsvdWtONHpkdFV2aTBm
            R0lPK0QrZkJ2ZENLZ2VnZ1pxaWZmd1UKLS0tIFdCNEI4SDE4S2p4VHJqNXdmallo
            dS9UNFBBYUhaV2J5UG42dkNCZnRNeW8K5k1lHXtN2jv1IVTrhk+XcfMWbOZUZ2eI
            YGqwctkuRs68JDCSoC28Eq1+cYQ0RzGoxM1oi/5muYdPhNX078njlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10tprfx4m37fahf3sz2hk9vvpte7kmjgmptnqhs8xhqwcn5vcsges047kwh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNEY4NStFcXdISGJvOTQ2
            UmhrK0N0RkY5M1FGUXdCcThkOUZRa01MOERFCmNjR1BXbTlDTVEyenF5ZGJsMTJo
            c1JXY0VFdG1kVjUyRllOakJHSENrZlEKLS0tIElCN2hlYnR1WGVkUVg3cHlCWVFi
            aHRwZVc4ZUNLNGZkd01PV3BBQjZHZkEKABNPx5X40fIuRHOW1Evu+sS5mVXjZSJG
            mgELTUA8Q6a/glw7QIxkAbTDyuwQ62uqodJN5Tx1Qjmm/efDdY0V+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-26T05:59:11Z"
    mac: ENC[AES256_GCM,data:6PFHOR1JPeOkocmrD2ygUAxmjWdVwhOIPuB+B2YBwrTdOmc862GzPwjGAVehb3HPKPvS5wVT6KOkmJJBsIz/BwwV34En203VgPDHN2uKCEUSTZt1oPmesqwdSrOmrFqVVIKLEK+FPzUmRFL2PC9oW0Q2VcuTVyRBk20cLiUXyKA=,iv:CHQs21iYYq+NivOJFglPgZ2XD7CYgF+2nZdBkzSDYJg=,tag:R++2yLH9KHNxQUtVhkmZQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
